name: newsline
description: An app which brings to you the latest News based on your location.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For network calls and interactions
  http: ^0.12.0+2

  # To access user's location and perform geocoding for co-ordinates
  geolocator: ^5.0.1

  # For app level state management
  provider: ^3.0.0+1

  # To provide an on-device sql database for offline persistence
  sqflite: ^1.1.5

  # To access the FontAwesome Icons library in-app
  font_awesome_flutter: ^8.4.0

  # To find commonly used locations in the device filesystem
  path_provider: ^0.5.0+1

  # To provide tools for reactive programming
  rxdart: ^0.22.0

  # To use svg in project
  flutter_svg: ^0.13.0+2

  # To use international formats
  intl: any

  # To open article urls
  flutter_custom_tabs: ^0.6.0

  # To cache images from the network on device
  cached_network_image: ^0.8.0

  # To share news to other platforms
  share: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any # A package to test flutter apps


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image/news.svg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
